cursor #4e3829
cursor_text_color #644735

foreground            #4e3829
background            #f9f5d7
selection_foreground  #f3eac7
selection_background  #b37109
url_color             #6b782e

color0   #141617
color1   #792c1f
color2   #1a5f12
color3   #99840b
color4   #6f7e2c
color5   #cdd4aa
color6   #6b782e
color7   #232321
color8   #6b6c69
color9   #ad584a
color10  #368c2d
color11  #a59016
color12  #798a2c
color13  #cdd4aa
color14  #939c6b
color15  #bebfba
